In [2]:
# import the library
from inmetpy.stations import InmetStation
inmet = InmetStation()

# list all inmet stations available
stations = inmet.get_stations() # get details of all stations available

auto_stations = inmet.get_stations("A") # details of all automatic stations
manual_stations = inmet.get_stations("M") # details of all manual stations

In [3]:
auto_stations

,CD_OSCAR,STATION_NAME,CD_STATION,TP_STATION,START_DATE_OPERATION,END_DATE_OPERATION,LONGITUDE,LATITUDE,HEIGHT,CD_SITUATION,CD_WSI,IS_CAPITAL,CD_DISTRICT,INSTITUTE,STATE
0,0-2000-0-86765,ABROLHOS,A422,Automatic,2008-07-21 00:00:00+00:00,NaT,-38.703333,-17.963056,20.93,Down,0-76-0-2906907000000408,False,04,INMET,BA
1,0-2000-0-81755,ACARAU,A360,Automatic,2009-04-22 00:00:00+00:00,NaT,-40.087222,-3.121111,67.15,Operative,0-76-0-2300200000000446,False,03,INMET,CE
2,0-2000-0-86827,AFONSO CLAUDIO,A657,Automatic,2011-09-24 00:00:00+00:00,NaT,-41.106944,-20.104167,507.48,Operative,0-76-0-3200102000000478,False,06,INMET,ES
3,0-2000-0-86686,AGUA BOA,A908,Automatic,2006-12-16 00:00:00+00:00,NaT,-52.211667,-14.016389,440.00,Down,0-76-0-5100201000000157,False,09,INMET,MT
4,0-2000-0-86812,AGUA CLARA,A756,Automatic,2010-08-14 00:00:00+00:00,NaT,-52.875833,-20.444444,323.63,Operative,0-76-0-5000203000000463,False,07,INMET,MS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,0-2000-0-86830,VITORIA,A612,Automatic,2006-10-31 00:00:00+00:00,NaT,-40.305833,-20.270833,9.00,Operative,0-76-0-3205309000000130,False,06,INMET,ES
563,0-2000-0-86697,VITORIA DA CONQUISTA,A414,Automatic,2007-06-01 00:00:00+00:00,NaT,-40.801389,-14.886389,879.38,Operative,0-76-0-2933307000000204,False,04,INMET,BA
564,0-2000-0-86940,XANXERE,A858,Automatic,2008-03-15 00:00:00+00:00,NaT,-52.398090,-26.938666,878.74,Operative,0-76-0-4219507000000318,False,08,INMET,SC
565,0-2000-0-81896,XINGUARA,A247,Automatic,2016-09-11 00:00:00+00:00,NaT,-49.926111,-7.110556,245.00,Operative,0-76-0-1508407000000527,False,02,INMET,PA
566,0-2000-0-81747,ZE DOCA,A255,Automatic,2019-09-18 00:00:00+00:00,NaT,-45.651111,-3.269167,45.50,Operative,0-76-0-2114007000000596,False,02,INMET,MA

In [7]:

# get data from all inmet station after a selected date
inmet.get_all_stations(2021-09-01) # date in format YYYY-MM-DD"

404

In [ ]:
# get data from a station or a list of stations
inmet.get_data_station(start_date, end_date, by, station_id) # stations must be a list of strings with the "CD_STATION" (ID) of the stations desired.